# Generated by Django 4.1.1 on 2022-09-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True, verbose_name='discounted'),
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True, verbose_name='sub_total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True, verbose_name='total'),
        ),
    ]
